Validate PR title (#1386)
* Validate PR title

Move to a label to title prefix.

* Fix payload access

* Try failing properly

diff --git a/.github/workflows/changelog.yaml b/.github/workflows/changelog.yaml
--- a/.github/workflows/changelog.yaml
+++ b/.github/workflows/changelog.yaml
@@ -1,27 +1,37 @@
 name: "Ensure labels"
 on: # yamllint disable-line rule:truthy
-    pull_request:
-        types:
-            - labeled
-            - unlabeled
-            - opened
-            - synchronize
-            - reopened
-            - ready_for_review
+  pull_request:
+    types:
+      - labeled
+      - unlabeled
+      - opened
+      - synchronize
+      - reopened
+      - ready_for_review
 
 jobs:
-    changelog:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Check changelog label
-              if: github.event.pull_request.draft == false && false == contains(join(github.event.pull_request.labels.*.name, ','), 'changelog/')
-              run: |-
-                  echo "::error::Add 'changelog/*' label";
-                  exit 1;
-            - name: Check resource label
-              if: github.event.pull_request.draft == false && false == contains(join(github.event.pull_request.labels.*.name, ','), 'changelog/note') && false == contains(join(github.event.pull_request.labels.*.name, ','), 'changelog/no-changelog') && false == contains(join(github.event.pull_request.labels.*.name, ','), 'resource/')
-              run: |-
-                  echo "::error::Add 'resource/*' label";
-                  exit 1;
-            - name: OK
-              run: echo "Thank you!"
+  changelog:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check changelog label
+        if: github.event.pull_request.draft == false && false == contains(join(github.event.pull_request.labels.*.name, ','), 'changelog/')
+        run: |-
+          echo "::error::Add 'changelog/*' label";
+          exit 1;
+      - name: Get GitHub App token
+        id: get_token
+        uses: tibdex/github-app-token@v1
+        with:
+          app_id: ${{ secrets.PIPELINE_GITHUB_APP_ID }}
+          private_key: ${{ secrets.PIPELINE_GITHUB_APP_PRIVATE_KEY }}
+      - name: Check PR title
+        if: github.event.pull_request.draft == false && false == contains(join(github.event.pull_request.labels.*.name, ','), 'changelog/note') && false == contains(join(github.event.pull_request.labels.*.name, ','), 'changelog/no-changelog')
+        uses: actions/github-script@v5
+        with:
+          github-token: ${{ steps.get_token.outputs.token }}
+          script: |
+            const re = new RegExp('\\[\\w+\\] \\w+');
+            const title = context.payload.pull_request.title;
+            if (!re.test(title)) {
+              core.setFailed("Invalid title format: use '[resource_name] Description'");
+            }
